ASP.Core/Geografia/Geografia/Models/ErrorViewModel.cs
using System;

namespace Geografia.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.Core/Geografia/Geografia/Models/GeografiaContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Geografia.Models
{
    public class GeografiaContext : DbContext
    {
        public GeografiaContext(DbContextOptions<GeografiaContext> options) : base(options)
        {
        }
        public DbSet<Paise> Paise { get; set; }
    }
}

ASP.Core/Geografia/Geografia/Models/Paise.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Geografia.Models
{
    public class Paise
    {
        [Key]
        [Display(Name = "Indice")]
        public int Paid { get; set; }

        [Required(ErrorMessage = "Ingresa nombre")]
        [Display(Name = "Nombre del pais")]
        public string Paname { get; set; }

        [Required(ErrorMessage = "Ingresa capital")]
        [Display(Name = "Capital")]
        public string Pacapital { get; set; }

        [Required(ErrorMessage = "Ingresa continente")]
        [Display(Name = "Continente")]
        public string Continente { get; set; }

        [Required(ErrorMessage = "Ingresa numero de habitantes")]
        [Display(Name = "Numero de habitantes")]
        public int Habitantes { get; set; }

   
    }
}

ASP.Core/Geografia/Geografia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Geografia.Models;

namespace Geografia.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.Core/Geografia/Geografia/Controllers/PaiseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Geografia.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace Geografia.Controllers
{
    public class PaiseController : Controller
    {
        /*Varibale para accder a base de datos*/
        private readonly GeografiaContext _db;

        /*Constructor*/
        public PaiseController(GeografiaContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Paise.ToList();
            return View(displaydata);

        }

        [HttpGet]
        public async Task<IActionResult> Index(string PaiSearch)
        {
            ViewData["GetPaiseDetail"] = PaiSearch;
            var Cliquery = from x in _db.Paise select x;
            if (!String.IsNullOrEmpty(PaiSearch))
            {
                Cliquery = Cliquery.Where(x => x.Paname.Contains(PaiSearch) ||
                x.Pacapital.Contains(PaiSearch));
            }
            return View(await Cliquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Paise nPai)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nPai);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nPai);

        }
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getPaiDetail = await _db.Paise.FindAsync(id);
            return View(getPaiDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getPaiDetail = await _db.Paise.FindAsync(id);
            return View(getPaiDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Paise oldPai)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldPai);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldPai);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getPaiDetail = await _db.Paise.FindAsync(id);
            return View(getPaiDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getPaiDetail = await _db.Paise.FindAsync(id);
            _db.Paise.Remove(getPaiDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

ASP.Core/Geografia/Geografia/Views/Paise/Create.cshtml
@model Geografia.Models.Paise

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Paise</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Paname" class="control-label"></label>
                <input asp-for="Paname" class="form-control" />
                <span asp-validation-for="Paname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pacapital" class="control-label"></label>
                <input asp-for="Pacapital" class="form-control" />
                <span asp-validation-for="Pacapital" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continente" class="control-label"></label>
                <input asp-for="Continente" class="form-control" />
                <span asp-validation-for="Continente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitantes" class="control-label"></label>
                <input asp-for="Habitantes" class="form-control" />
                <span asp-validation-for="Habitantes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.Core/Geografia/Geografia/Views/Paise/Delete.cshtml
@model Geografia.Models.Paise

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paise</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pacapital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pacapital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Continente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Continente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Habitantes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Habitantes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP.Core/Geografia/Geografia/Views/Paise/Detail.cshtml
@model Geografia.Models.Paise

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Paise</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pacapital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pacapital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Continente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Continente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Habitantes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Habitantes)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ASP.Core/Geografia/Geografia/Views/Paise/Edit.cshtml
@model Geografia.Models.Paise

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Paise</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Paid" class="control-label"></label>
                <input asp-for="Paid" class="form-control" />
                <span asp-validation-for="Paid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paname" class="control-label"></label>
                <input asp-for="Paname" class="form-control" />
                <span asp-validation-for="Paname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pacapital" class="control-label"></label>
                <input asp-for="Pacapital" class="form-control" />
                <span asp-validation-for="Pacapital" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continente" class="control-label"></label>
                <input asp-for="Continente" class="form-control" />
                <span asp-validation-for="Continente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitantes" class="control-label"></label>
                <input asp-for="Habitantes" class="form-control" />
                <span asp-validation-for="Habitantes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.Core/Geografia/Geografia/Views/Paise/Index.cshtml
@model IEnumerable<Geografia.Models.Paise>

@{
    ViewData["Title"] = "Index";
}

<h1>Pagina Principal</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" method="get">
    <p>
        <i class=" fa fa-search"></i>
        <input type="search" placeholder=" Ingresa Nombre o Capital..." name="PaiSearch"
               value="@ViewData["GetPaiseDetail"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver todos</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Paid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacapital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Continente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Habitantes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Paid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Paname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pacapital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Continente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Habitantes)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Paid }, new { @class = "btn btn-primary" })  |
                @Html.ActionLink("Detail", "Detail", new { id = item.Paid }, new { @class = "btn btn-success" })  |
                @Html.ActionLink("Delete", "Delete", new { id = item.Paid }, new { @class = "btn btn-danger" })
            </td>
        </tr>

     
}
    </tbody>
</table>

ASP.Core/Geografia/Geografia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Geografia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Geografia</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paise" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Geografia 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>